### PR TITLE
Sets the version to 1.0.5.12 to match QuantConnect's nuget one.

### PR DESCRIPTION
**Pull request by AlexCatarino**

### CODE REVIEW

**Comment by mchandschuh** [comment]
Looks great, thanks!

**Comment by mchandschuh** [comment]
Also, we'll need to be diligent moving forward to ensure we keep the assembly version in sync with the nuget version. I'll add it to my PR checklist for this repository.

**Comment by beemaninsuranceagents** [comment]
@beemaninsuranceagents

**Comment by beemaninsuranceagents** [comment]
files changed

**Pull request merged**
